### ISSUE TITLE
How to verify if `"viml.highVimHelpIndentStylePriority": true` is in effect?

### ISSUE THREAD

**Issue by wenfangdu** [XadillaX/vscode-language-viml#22]
I tried toggling this setting, seems nothing has changed.

**Comment by XadillaX** [comment]
Try to use editorconfig, and set all indents to 2. Then toggle this setting. You'll see 2 indent when disabled and tab indent when enabled in VimHelp file.

**Comment by wenfangdu** [comment]
> and _**tab**_ indent when enabled in VimHelp file.

You mean 8 indents?

**Comment by wenfangdu** [comment]
> and _**tab**_ indent when enabled in VimHelp file.

@XadillaX You mean 8 indents?

**Comment by XadillaX** [comment]
> > and _**tab**_ indent when enabled in VimHelp file.
> 
> @XadillaX You mean 8 indents?

yes.

**Comment by wenfangdu** [comment]
@XadillaX Dude, you're not lagging at all :D.
