### ISSUE TITLE
How to tweak the number of spaces inserted after the comment character `"`

### ISSUE THREAD

**Issue by gaochenyi** [XadillaX/vscode-language-viml#30]
Hi, thanks for developing this extension.

I'd like to change the number of spaces inserted after `"` to 1 (instead of the default 2). How to achieve this? There seems no option for this?

**Comment by XadillaX** [comment]
We didn't change the spaces count after `"`. If you type `"` + `<space>` + `f`, the result will be `" f`, not `"<double spaces>f`.

**Comment by gaochenyi** [comment]
> We didn't change the spaces count after `"`. If you type `"` + `<space>` + `f`, the result will be `" f`, not `"<double spaces>f`.

Oh, sorry for the vagueness. I mean toggling line comment by `<cmd>` + `/`---This extension inserts `"<double spaces>`. I want to have it insert only one space after the commenting `"`. Is this possible?

**Comment by XadillaX** [comment]
It seems that I've no good idea to deal with it now. Because I set comment sign to `" ` (quote + space). If I set it to a single quote, then vscode will mismatch string quote.

**Comment by wenfangdu** [comment]
Fixed by #38.

**Comment by XadillaX** [comment]
published in v2.2.0
