### ISSUE TITLE
[Bug] Request textDocument/completion failed

### ISSUE THREAD

**Issue by wenfangdu** [XadillaX/vscode-language-viml#36]
Repro Steps:

1. Put the cursor at the start of a line.
2. Use `"editor.action.triggerSuggest"`.

![image](https://user-images.githubusercontent.com/28700378/177946547-87c273c5-41d5-46c3-9305-00a6a97d57c3.png)

**Comment by XadillaX** [comment]
I use https://www.npmjs.com/package/vim-language-server for language server. So maybe it's the issue of vim-language-server.

**Comment by wenfangdu** [comment]
@XadillaX Looks like it's already been fixed:

https://github.com/iamcco/vim-language-server/commit/5d7027f7ac50fb6679b073b4c1f515f4a3c2d032#diff-ba58f348990cdb73794c3b09904e7a51fed5a9373e2aebfcbe87046206b99591R135
