### ISSUE TITLE
.ideavimrc file type

### ISSUE THREAD

**Issue by Moortu** [XadillaX/vscode-language-viml#4]
IdeaVim actually uses .ideavimrc as specified in https://github.com/JetBrains/ideavim

So could .ideavimrc be added to supported filetype

**Comment by davidde** [comment]
Add to that the `vimrc` and `nvimrc` files without the leading dot. It is quite annoying they are left out from syntax highlighting.

**Comment by XadillaX** [comment]
https://github.com/XadillaX/vscode-language-viml/commit/1b1323f40525a92663e8ac26af2127ff7063858e
