### ISSUE TITLE
Syntax highlighting for .vroom files

### ISSUE THREAD

**Issue by dbarnett** [XadillaX/vscode-language-viml#45]
Hello, would you consider including syntax highlighting for vim-related .vroom test files along with the others?

[vroom](https://github.com/google/vroom) is a literate testing tool for vim plugins and [the syntax](https://github.com/vim/vim/blob/master/runtime/syntax/vroom.vim) is just a thin wrapper around vimscript syntax, that's already supported out-of-the-box in vim.

**Comment by XadillaX** [comment]
Let me learn about vroom first :)

**Comment by XadillaX** [comment]
published in v2.2.0
