### ISSUE TITLE
FR: please co-publish on open-vsx

### ISSUE THREAD

**Issue by GitMensch** [XadillaX/vscode-language-viml#6]
For details see [Publishing Extensions on open-vsx.org](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension), it would be good to have this extension not only in the ms marketplace but also available in a place that does not explicit forbid to use it with anything else than a Visual Studio product or a browser.

**Comment by GitMensch** [comment]
Friendly ping: is this something you consider to do?

**Comment by XadillaX** [comment]
Sorry for late reply. I will try to publish to open vsx later. Thanks for advising.

**Comment by XadillaX** [comment]
I've already published it to open-vsx: https://open-vsx.org/extension/XadillaX/viml

**Comment by GitMensch** [comment]
Sadly 2.2 wasn't updated on OpenVSX.

You may want to switch publishing to a [GitHub action](https://docs.github.com/en/actions) that allows publishing to both market places, one option would be [HaaLeo/publish-vscode-extension](https://github.com/HaaLeo/publish-vscode-extension#readme).

**Comment by GitMensch** [comment]
ping @XadillaX concerning the outdated version
