### ISSUE TITLE
FR: add "layout support" to the TODO

### ISSUE THREAD

**Issue by GitMensch** [XadillaX/vscode-language-viml#7]
And possibly, somedayTM even add it (I'm not aware of any viml extension that has that yet - it would really make the extension stand out).

**Comment by XadillaX** [comment]
Could you give some more information? I'm not sure what does "add "layout support" to the TODO" mean

**Comment by GitMensch** [comment]
I've meant to extend the [README](https://github.com/XadillaX/vscode-language-viml#todo) to include an entry for "add outline for viml" which would show the function (and possibly variable) definitions.

**Comment by GitMensch** [comment]
Note: "related" but using a different api and more important is #8

**Comment by GitMensch** [comment]
Hm, more research leads to a [SO answer](https://stackoverflow.com/a/59132169/5027456) that says "this will be available automatically when a [DocumentSymbolProvider](https://code.visualstudio.com/api/references/vscode-api#DocumentSymbolProvider) is registered which declares the functions correctly, so may actually be solved by #8.

**Comment by XadillaX** [comment]
Finished

**Comment by XadillaX** [comment]
@all-contributors Please add @GitMensch for ideas.
