### ISSUE TITLE
please add symbol provider (would allow "go to" / "show definition/references")

### ISSUE THREAD

**Issue by GitMensch** [XadillaX/vscode-language-viml#8]
... and possibly improves on one of the TODO points, providing (at least a bit of) better code-completion.

**Comment by GitMensch** [comment]
Thank you for your recent work on this extension. After updating I've thought about what I miss most - it is definitely the symbol providing part. Some first research shows that to do it one needs to provide a [DocumentSymbolProvider](https://code.visualstudio.com/api/references/vscode-api#DocumentSymbolProvider), there's an [example for this at SO](https://stackoverflow.com/questions/46045245/how-to-enable-go-to-symbol-with-a-custom-language-in-vscode/46054953#46054953).

The first thing to provide would be function definitions, the second one variables.

**Comment by XadillaX** [comment]
Finished

**Comment by GitMensch** [comment]
That is so super cool, thank you very much for [version 2.0.0](https://github.com/XadillaX/vscode-language-viml/releases/tag/v2.0.0)! That totally changes the way to work with vimL files!
