### ISSUE TITLE
FR: add CHANGELOG.md

### ISSUE THREAD

**Issue by GitMensch** [XadillaX/vscode-language-viml#9]
Doesn't need to contain much but as this shows in the market places it is commonly useful to have it with some minimal content in - and also is a service to the users to know about the updates without checking the git diff. Maybe good to do together with #6.

**Comment by XadillaX** [comment]
Done in https://github.com/XadillaX/vscode-language-viml/commit/6b1b3286adc6904e9ac89336731a59d14b627f61
